### ISSUE TITLE
Build fails due to `Unknown archive format` on Mac

### ISSUE THREAD

**Issue by KyleMiles** [emscripten-core/emsdk#982]
I just installed emscripten on my Mac following the instructions at https://emscripten.org/docs/getting_started/downloads.html, cloned a project that compiles fine on Linux, and when I try compile on Mac (M1) I get the following error:

```
note: shared:INFO: (Emscripten: Running sanity checks)
      ports:INFO: retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
      ports:INFO: unpacking port: freetype
      cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libfreetype.a... (this will be cached in "/projectdir/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a" for subsequent builds)
      cache:INFO:  - ok
      ports:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/2.8.1/harfbuzz-2.8.1.tar.xz
      ports:INFO: unpacking port: harfbuzz
      Traceback (most recent call last):
        File "/projectdir/emsdk/upstream/emscripten/emcc.py", line 3943, in <module>
          sys.exit(main(sys.argv))
        File "/projectdir/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
          return func(*args, **kwds)
        File "/projectdir/emsdk/upstream/emscripten/emcc.py", line 3936, in main
          ret = run(args)
        File "/projectdir/emsdk/upstream/emscripten/emcc.py", line 1138, in run
          phase_calculate_system_libraries(state, linker_arguments, linker_inputs, newargs)
        File "/projectdir/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
          return func(*args, **kwds)
        File "/projectdir/emsdk/upstream/emscripten/emcc.py", line 2642, in phase_calculate_system_libraries
          extra_files_to_link += ports.get_libs(settings)
        File "/projectdir/emsdk/upstream/emscripten/tools/ports/__init__.py", line 342, in get_libs
          ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
        File "/projectdir/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 82, in get
          ports.fetch_project('harfbuzz', 'https://github.com/harfbuzz/harfbuzz/releases/download/' +
        File "/projectdir/emsdk/upstream/emscripten/tools/ports/__init__.py", line 259, in fetch_project
          unpack()
        File "/projectdir/emsdk/upstream/emscripten/tools/ports/__init__.py", line 232, in unpack
          shutil.unpack_archive(filename=fullpath, extract_dir=fullname)
        File "/projectdir/emsdk/python/3.9.2_64bit/lib/python3.9/shutil.py", line 1241, in unpack_archive
          raise ReadError("Unknown archive format '{0}'".format(filename))
      shutil.ReadError: Unknown archive format '/projectdir/emsdk/upstream/emscripten/cache/ports/harfbuzz.8.1.tar.xz'
```

Going by closed issues/PRs It appears that this issue was fixed recently, but either `./emsdk install latest` isn't getting the most recent changes, or those changes aren't working for me.

**Comment by sbc100** [comment]
This looks like the same issue as https://github.com/emscripten-core/emscripten/issues/16073.

I fixed it for x86_64 in #975 but a fix for M1 would require somebody to rebuilt python on that plaform.  @dschuff do you have access to an M1 mac?  (Or maybe @juj?)

**Comment by KyleMiles** [comment]
I've got an M1, if you point me to what commands to run, I'm happy to upload the file.

**Comment by sbc100** [comment]
The script to run is `./scripts/update_python.py`.   I will fail at the last step of uploading the file, but if you get that far you could attach the result to this issue.

Bear in mind that the script is a little hacky and both installs and then modifies in-place some homebrew packages.. run at your own risk (or take a look at what its doing and make sure you are ok with it :)

**Comment by sbc100** [comment]
Actually.. can you try a work-around?   Can you try setting `EMSDK_PYTHON=/path/to/system/python` when you do the build that installs harfbuzz (you might need to install the official python3 from somewhere I'm not sure).

**Comment by KyleMiles** [comment]
Running my build with `EMSDK_PYTHON=/usr/bin/python3` works perfectly!

For reference, I believe that's the default Python install, which is giving me version `Python 3.8.9`.

**Comment by sbc100** [comment]
IIRC the situation with macOS pre-installed python is complicated.   See https://xkcd.com/1987/.  

I've heard that sometimes python3 can be a symbolic link it an installer?  And also that apple doesn't want folks relying on the system version.   Do you know if /usr/bin/python3 came with your system or was it later installed?  Perhaps the situation with the latest macOS has changed and we can/should start assuming /usr/bin/python3 exists?

**Comment by sbc100** [comment]
I believe this was fixed in #975

**Comment by MrColour** [comment]
If you are getting an error like:

```      
ports:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/2.8.1/harfbuzz-2.8.1.tar.xz
      ports:INFO: unpacking port: harfbuzz
      Traceback (most recent call last):
        File "/projectdir/emsdk/upstream/emscripten/emcc.py", line 3943, in <module>
          sys.exit(main(sys.argv))
```

When trying to build on a M1 mac (my macOS version: Ventura 13.3.1 (a)) when running an emcc line that includes `USE_SDL_TTF=2` you can try setting the following shell or environment variable `EMSDK_PYTHON=/path/to/system/python` (https://www.purdue.edu/hla/sites/varalalab/wp-content/uploads/sites/20/2018/02/Lecture_5.pdf, basically run `EMSDK_PYTHON=/path/to/system/python` in the shell, you can also try `EMSDK_PYTHON=/path/to/system/python3`).

You will also want to ensure that your mac runs python, you can check this with the command `which python` or `which python3` and you should get something like: `/opt/homebrew/bin/python3`.

When the command `emcc` compiles your program it will get the hint that to use the python path that was declared in the environment/shell `EMSDK_PYTHON` which should allow it to successfully compile harfbuzz-2.8.1 that is required when using SDL_ttf.

**Comment by albertvaka** [comment]
Has the fix been released? As of today, after installing with `emsdk install latest` I still get `shutil.ReadError: Unknown archive format '/Users/albert.cintora/emsdk/upstream/emscripten/cache/ports/harfbuzz.2.0.tar.xz'` unless I define `EMSDK_PYTHON=/usr/bin/python3`

**Comment by NHDaly** [comment]
+1 to @albertvaka's comment, for me.
```
export EMSDK_PYTHON=/usr/bin/python3
```
Did indeed resolve this for me. Thanks
